LOAD DATA LOCAL INFILE 'user-data.csv' INTO TABLE Users
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'item-data.csv' INTO TABLE Items
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'bid-data.csv' INTO TABLE Bids
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'category-data.csv' INTO TABLE Categories
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'location-data.csv' INTO TABLE UserLocation
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
