LOAD DATA LOCAL INFILE 'src/user-data.csv' INTO TABLE Users
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'src/item-data.csv' INTO TABLE Items
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'src/bid-data.csv' INTO TABLE Bids
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'src/category-data.csv' INTO TABLE Categories
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'src/latlong-data.csv' INTO TABLE LatLong
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'src/location-data.csv' INTO TABLE UserLocation
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
